name: Continuous Integration
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: bundle-use-ruby-${{ runner.os }}
    - run: bundle install --jobs 4 --retry 3 --deployment
    - run: bundle exec rake
